apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output

  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string
    - name: build-image
      type: string

  tasks:

    # 1️⃣ cleanup
    - name: cleanup
      taskRef:
        name: cleanup
        kind: Task
      workspaces:
        - name: source
          workspace: output

    # 2️⃣ git clone (ClusterTask)
    - name: git-clone
      runAfter: ["cleanup"]
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: output

    # 3️⃣ nose tests
    - name: test
      runAfter: ["git-clone"]
      taskRef:
        name: nose
        kind: Task
      workspaces:
        - name: source
          workspace: output

    # 4️⃣ buildah (ClusterTask)
    - name: build
      runAfter: ["test"]
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    # 5️⃣ deploy (ClusterTask)
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
